export const options = [
    { value: '10cc Sailine Flushes', label: '10cc Sailine Flushes' },
    { value: 'Ace Bandage - 3"', label: 'Ace Bandage - 3"' },
    { value: 'Ace Bandages - 4" inch', label: 'Ace Bandages - 4" inch' },
    { value: 'Acetaminophen - 500mg - 100 count bottle', label: 'Acetaminophen - 500mg - 100 count bottle' },
    { value: 'Acetaminophen - 500mg - Single Dose Packet', label: 'Acetaminophen - 500mg - Single Dose Packet' },
    { value: 'Advil - 200mg - Single Dose Packet', label: 'Advil - 200mg - Single Dose Packet' },
    { value: 'AED', label: 'AED' },
    { value: 'AED Pad', label: 'AED Pad' },
    { value: 'AED/CPR Responder Pack', label: 'AED/CPR Responder Pack' },
    { value: 'Afrin', label: 'Afrin' },
    { value: 'Afterbite Wipes', label: 'Afterbite Wipes' },
    { value: 'Airborne - bottle of 32 chewable tablets', label: 'Airborne - bottle of 32 chewable tablets' },
    { value: 'Albuterol Inhaler - Ventolin HFA 90mcg - 8gm/60 doses', label: 'Albuterol Inhaler - Ventolin HFA 90mcg - 8gm/60 doses' },
    { value: 'Alcohol Pads', label: 'Alcohol Pads' },
    { value: 'Alcohol Wipes', label: 'Alcohol Wipes' },
    { value: 'Ambu Bag - Adult', label: 'Ambu Bag - Adult' },
    { value: 'Angio Cath - 18G', label: 'Angio Cath - 18G' },
    { value: 'Angio Cath - 20G', label: 'Angio Cath - 20G' },
    { value: 'Angio Cath - 22G', label: 'Angio Cath - 22G' },
    { value: 'Antacid Tabs (Alcalak) - Single Dose Packet', label: 'Antacid Tabs (Alcalak) - Single Dose Packet' },
    { value: 'Aspirin - 81mg - chewable 36 tabs per bottle', label: 'Aspirin - 81mg - chewable 36 tabs per bottle' },
    { value: 'Avery Labels', label: 'Avery Labels' },
    { value: 'AZO Urinary Relief Tabs', label: 'AZO Urinary Relief Tabs' },
    { value: 'Bacitracin Antibiotic Ointment - Single Packet', label: 'Bacitracin Antibiotic Ointment - Single Packet' },
    { value: 'Bandaids - Fabric - Large', label: 'Bandaids - Fabric - Large' },
    { value: 'Bandaids - Fabric - Standard', label: 'Bandaids - Fabric - Standard' },
    { value: 'Band-Aids - Large', label: 'Band-Aids - Large' },
    { value: 'Band-Aids - Regular', label: 'Band-Aids - Regular' },
    { value: 'Batteries - AA & C - 2 of each, AAA-6', label: 'Batteries - AA & C - 2 of each, AAA-6' },
    { value: 'Batteries - CR2032 3V Lithium', label: 'Batteries - CR2032 3V Lithium' },
    { value: 'BioGlo Fluorescein Strips', label: 'BioGlo Fluorescein Strips' },
    { value: 'Burn Dressing - WaterJel 4"x4"', label: 'Burn Dressing - WaterJel 4"x4"' },
    { value: 'Cohesive Bandage - 3"', label: 'Cohesive Bandage - 3"' },
    { value: 'Cold Compress', label: 'Cold Compress' },
    { value: 'Cotton Balls', label: 'Cotton Balls' },
    { value: 'Cotton Tipped Applicator - tube of 6/each', label: 'Cotton Tipped Applicator - tube of 6/each' },
    { value: 'Cough Drops - 10 packets of 5/each', label: 'Cough Drops - 10 packets of 5/each' },
    { value: 'Covid Test - Antigen- For symptomatic testing', label: 'Covid Test - Antigen- For symptomatic testing' },
    { value: 'CPR Pocket Mask', label: 'CPR Pocket Mask' },
    { value: 'Deep Sea Saline Nasal Spray - 1.5 fl. oz.', label: 'Deep Sea Saline Nasal Spray - 1.5 fl. oz.' },
    { value: 'Dermabond - ampule', label: 'Dermabond - ampule' },
    { value: 'Dexamethasone - 10mg/mL - 1mL Vial', label: 'Dexamethasone - 10mg/mL - 1mL Vial' },
    { value: 'Diphen(Benadryl) - 25mg - Single Dose Packet', label: 'Diphen(Benadryl) - 25mg - Single Dose Packet' },
    { value: 'Diphenhydramine - 25mg blister packs', label: 'Diphenhydramine - 25mg blister packs' },
    { value: 'Diphenhydramine - 25mg Single Dose Packet', label: 'Diphenhydramine - 25mg Single Dose Packet' },
    { value: 'Diphenhydramine 50mg/mL IM/IV diphenhydramine', label: 'Diphenhydramine 50mg/mL IM/IV diphenhydramine' },
    { value: 'Direct Laryngoscope with Mac 3 Blade', label: 'Direct Laryngoscope with Mac 3 Blade' },
    { value: 'Dispensing Envelopes', label: 'Dispensing Envelopes' },
    { value: 'Docusate - 100mg Softgels', label: 'Docusate - 100mg Softgels' },
    { value: 'DynaLube', label: 'DynaLube' },
    { value: 'Ear Curettes', label: 'Ear Curettes' },
    { value: 'Electronic BP Cuff', label: 'Electronic BP Cuff' },
    { value: 'Emesis Bags', label: 'Emesis Bags' },
    { value: 'Epinephrine Ampules - 1mg/mL Epi (1:1000)', label: 'Epinephrine Ampules - 1mg/mL Epi (1:1000)' },
    { value: 'Erythromycin Eye Ointment- tube', label: 'Erythromycin Eye Ointment- tube' },
    { value: 'Eye Pad', label: 'Eye Pad' },
    { value: 'Eye Wash - 4 fl. oz.', label: 'Eye Wash - 4 fl. oz.' },
    { value: 'FedEx Return Label - In Clear Pouch', label: 'FedEx Return Label - In Clear Pouch' },
    { value: 'Filter Needle - 18 gauge', label: 'Filter Needle - 18 gauge' },
    { value: 'Finger Splint - Small & Large', label: 'Finger Splint - Small & Large' },
    { value: 'FluoroDot Light - Blue', label: 'FluoroDot Light - Blue' },
    { value: 'Gallon Baggie with sticker, for malfunctioning test parts', label: 'Gallon Baggie with sticker, for malfunctioning test parts' },
    { value: 'Gauze Pad - 2x2 Sterile', label: 'Gauze Pad - 2x2 Sterile' },
    { value: 'Gauze Pad - 4x4 Sterile', label: 'Gauze Pad - 4x4 Sterile' },
    { value: 'Gauze Pads - 2" x 2"', label: 'Gauze Pads - 2" x 2"' },
    { value: 'Gloves - Large', label: 'Gloves - Large' },
    { value: 'Glucometer - True Metrix', label: 'Glucometer - True Metrix' },
    { value: 'Glucose Lancets', label: 'Glucose Lancets' },
    { value: 'Glucose Tablets - 10 pack', label: 'Glucose Tablets - 10 pack' },
    { value: 'Glucose Test Strips', label: 'Glucose Test Strips' },
    { value: 'Guaifenesin - 400mg tablets', label: 'Guaifenesin - 400mg tablets' },
    { value: 'Hand Sanitizer - 1 oz.', label: 'Hand Sanitizer - 1 oz.' },
    { value: 'Heat packs (Adhesive Heat Therapy)', label: 'Heat packs (Adhesive Heat Therapy)' },
    { value: 'Hydration Packets', label: 'Hydration Packets' },
    { value: 'Hydrocortisone Cream 1% - Single Dose Packet', label: 'Hydrocortisone Cream 1% - Single Dose Packet' },
    { value: 'Hydrogen Peroxide 8oz bottle', label: 'Hydrogen Peroxide 8oz bottle' },
    { value: 'I.V. Solution - Sodium Chloride 500ml', label: 'I.V. Solution - Sodium Chloride 500ml' },
    { value: 'I.V. Start Kit', label: 'I.V. Start Kit' },
    { value: 'I.V. Tubing', label: 'I.V. Tubing' },
    { value: 'Ibuprofen - 200mg - 200 count', label: 'Ibuprofen - 200mg - 200 count' },
    { value: 'Ibuprofen - 200mg - Single Dose Packet', label: 'Ibuprofen - 200mg - Single Dose Packet' },
    { value: 'IHP Medication Bags (Pharmacy bags)', label: 'IHP Medication Bags (Pharmacy bags)' },
    { value: 'IHP Zips', label: 'IHP Zips' },
    { value: 'Imodium (Loperamide) - 2mg tablets', label: 'Imodium (Loperamide) - 2mg tablets' },
    { value: 'Influenza Test Kit (To be placed in Gallon size baggie)', label: 'Influenza Test Kit (To be placed in Gallon size baggie)' },
    { value: 'Kerlix Bandages', label: 'Kerlix Bandages' },
    { value: 'Ketorolac Tromethamine - 60mg - 2mL Vial', label: 'Ketorolac Tromethamine - 60mg - 2mL Vial' },
    { value: 'Kleenex Tissues - Packet', label: 'Kleenex Tissues - Packet' },
    { value: 'Laceration Tray', label: 'Laceration Tray' },
    { value: 'Lidocaine HCI - 1% or 2% - 1/50mL or 2/20mL', label: 'Lidocaine HCI - 1% or 2% - 1/50mL or 2/20mL' },
    { value: 'Lidocaine HCI 2% w/ Epi 1:100,000 - 1/50mL or 2/20mL', label: 'Lidocaine HCI 2% w/ Epi 1:100,000 - 1/50mL or 2/20mL' },
    { value: 'LifeVac Choking Device- Ped and Adult Set', label: 'LifeVac Choking Device- Ped and Adult Set' },
    { value: 'Lip Balm', label: 'Lip Balm' },
    { value: 'Lock for unit combination (911)', label: 'Lock for unit combination (911)' },
    { value: 'Loratadine - 10mg tablets', label: 'Loratadine - 10mg tablets' },
    { value: 'Magill Forceps', label: 'Magill Forceps' },
    { value: 'Manual Suction Pump Kit', label: 'Manual Suction Pump Kit' },
    { value: 'Masks - N95 or KN95', label: 'Masks - N95 or KN95' },
    { value: 'Meclizine - 25mg tablets', label: 'Meclizine - 25mg tablets' },
    { value: 'Miralax Packets', label: 'Miralax Packets' },
    { value: 'Mole Skin - pieces', label: 'Mole Skin - pieces' },
    { value: 'Motion Sickness Patches', label: 'Motion Sickness Patches' },
    { value: 'Nail Clippers - cuticle style', label: 'Nail Clippers - cuticle style' },
    { value: 'Naloxone (Narcan) - 4mg Spray', label: 'Naloxone (Narcan) - 4mg Spray' },
    { value: 'Nasal Cannula - O2', label: 'Nasal Cannula - O2' },
    { value: 'Nasopharyngeal Airway Kit - two sizes', label: 'Nasopharyngeal Airway Kit - two sizes' },
    { value: 'Needle - 18g', label: 'Needle - 18g' },
    { value: 'Needle - 18g Filter', label: 'Needle - 18g Filter' },
    { value: 'Needle - 25 gauge', label: 'Needle - 25 gauge' },
    { value: 'Nitrostat - 0.4mg - 25 tablet bottle', label: 'Nitrostat - 0.4mg - 25 tablet bottle' },
    { value: 'Opti Chamber', label: 'Opti Chamber' },
    { value: 'Orajel- tube', label: 'Orajel- tube' },
    { value: 'Oropharyngeal Airway Kit', label: 'Oropharyngeal Airway Kit' },
    { value: 'Otoscope', label: 'Otoscope' },
    { value: 'Packaging Tape', label: 'Packaging Tape' },
    { value: 'Pain Off (Excedrin Migraine) - Single Dose Packet', label: 'Pain Off (Excedrin Migraine) - Single Dose Packet' },
    { value: 'Pataday Allergy Eyedrops', label: 'Pataday Allergy Eyedrops' },
    { value: 'Pepcid OTC 20mg tabs', label: 'Pepcid OTC 20mg tabs' },
    { value: 'Pepto Bismol - (Diotame) 5 single dose packets', label: 'Pepto Bismol - (Diotame) 5 single dose packets' },
    { value: 'Phenergan(Promethazine) oral 25mg each', label: 'Phenergan(Promethazine) oral 25mg each' },
    { value: 'Povidone Iodine Swabs', label: 'Povidone Iodine Swabs' },
    { value: 'Prilosec (Omeprazole) - 20mg', label: 'Prilosec (Omeprazole) - 20mg' },
    { value: 'Promethazine - 25mg/mL - 1mL Vial', label: 'Promethazine - 25mg/mL - 1mL Vial' },
    { value: 'Pulse Oximeter', label: 'Pulse Oximeter' },
    { value: 'Quick-Seal Nose Bleed Plugs (Baggie of 4)', label: 'Quick-Seal Nose Bleed Plugs (Baggie of 4)' },
    { value: 'R-15 Oxygen Concentrator', label: 'R-15 Oxygen Concentrator' },
    { value: 'Regular Adult Manual BP Cuff', label: 'Regular Adult Manual BP Cuff' },
    { value: 'Saljet Saline Bullets 0.9%', label: 'Saljet Saline Bullets 0.9%' },
    { value: 'Sam Splint', label: 'Sam Splint' },
    { value: 'Scalpel #11 Blade', label: 'Scalpel #11 Blade' },
    { value: 'Scrub Brush - BD EZ Scrub CHG 4% (Schein)', label: 'Scrub Brush - BD EZ Scrub CHG 4% (Schein)' },
    { value: 'Sharps Container - 1 quart (in box with medical unit)', label: 'Sharps Container - 1 quart (in box with medical unit)' },
    { value: 'Shaving Razor', label: 'Shaving Razor' },
    { value: 'Sodium Chloride - 0.9% - 250mL Irrigation Solution', label: 'Sodium Chloride - 0.9% - 250mL Irrigation Solution' },
    { value: 'Staple Gun', label: 'Staple Gun' },
    { value: 'Steri Strips 1 pack of each - 1/4" & 1/2"', label: 'Steri Strips 1 pack of each - 1/4" & 1/2"' },
    { value: 'Sterile Drapes', label: 'Sterile Drapes' },
    { value: 'Sterile Gloves Size 6, 7, 8', label: 'Sterile Gloves Size 6, 7, 8' },
    { value: 'Stethoscope', label: 'Stethoscope' },
    { value: 'Strep Tests (to be placed in gallon size baggie)', label: 'Strep Tests (to be placed in gallon size baggie)' },
    { value: 'Sudafed 30mg tabs', label: 'Sudafed 30mg tabs' },
    { value: 'Sunscreen Packets', label: 'Sunscreen Packets' },
    { value: 'Suture 4-0 Ethilon/FS-2 Needle - Schein', label: 'Suture 4-0 Ethilon/FS-2 Needle - Schein' },
    { value: 'Suture 5-0 Ethilon/P-3 Needle', label: 'Suture 5-0 Ethilon/P-3 Needle' },
    { value: 'Suture 6-0 Ethilon/C-2 Needle', label: 'Suture 6-0 Ethilon/C-2 Needle' },
    { value: 'Suture Removal Kit', label: 'Suture Removal Kit' },
    { value: 'Syringe - 1cc', label: 'Syringe - 1cc' },
    { value: 'Syringe - 20cc - no needle/Schein', label: 'Syringe - 20cc - no needle/Schein' },
    { value: 'Syringe - 3cc', label: 'Syringe - 3cc' },
    { value: 'Syringe w/29 gauge needle - 1cc', label: 'Syringe w/29 gauge needle - 1cc' },
    { value: 'Tampons- Regular', label: 'Tampons- Regular' },
    { value: 'Tape - 3M Transpore 1"', label: 'Tape - 3M Transpore 1"' },
    { value: 'Tape - Silk 1"', label: 'Tape - Silk 1"' },
    { value: 'Thera Tears-Rewetting drops- (6 packs of 5 individual dropers)', label: 'Thera Tears-Rewetting drops- (6 packs of 5 individual dropers)' },
    { value: 'Thermometer - Infrared', label: 'Thermometer - Infrared' },
    { value: 'Tongue Depressors', label: 'Tongue Depressors' },
    { value: 'Tourniquet - Emergency Outdoor', label: 'Tourniquet - Emergency Outdoor' },
    { value: 'Tranexamic Acid (TXA) 100mg/ml, 10ml vial', label: 'Tranexamic Acid (TXA) 100mg/ml, 10ml vial' },
    { value: 'Transport Tubes For Testing', label: 'Transport Tubes For Testing' },
    { value: 'Trauma Pad(Dukal Pad ABD/Combine 5x9)', label: 'Trauma Pad(Dukal Pad ABD/Combine 5x9)' },
    { value: 'Trauma Scissors', label: 'Trauma Scissors' },
    { value: 'Triangular Bandages', label: 'Triangular Bandages' },
    { value: 'Tweezers', label: 'Tweezers' },
    { value: 'Tylenol - 500mg - Single Dose Packet', label: 'Tylenol - 500mg - Single Dose Packet' },
    { value: 'Zip-Loc bags (1 gallon-size)', label: 'Zip-Loc bags (1 gallon-size)' },
    { value: 'Zip-Loc bags (Quart-size)', label: 'Zip-Loc bags (Quart-size)' },
    { value: 'PEDS (Unique Items)', label: 'PEDS (Unique Items)' },
    { value: 'Amoxicilllin Oral Suspension -400 mg/ml susp 100 ml', label: 'Amoxicilllin Oral Suspension -400 mg/ml susp 100 ml' },
    { value: 'Azithromycin Oral Suspension - 200mg per 5ml', label: 'Azithromycin Oral Suspension - 200mg per 5ml' },
    { value: 'Prednisolone Liquid - 15mg/5ml sol 237ml', label: 'Prednisolone Liquid - 15mg/5ml sol 237ml' },
    { value: 'Acetaminophen Oral Suspension - 160mg per ml - 4 fl oz', label: 'Acetaminophen Oral Suspension - 160mg per ml - 4 fl oz' },
    { value: 'Angiocath 24Gx.75"', label: 'Angiocath 24Gx.75"' },
    { value: 'Bandaids - Kids prints', label: 'Bandaids - Kids prints' },
    { value: 'Benzoin Compound Ampules', label: 'Benzoin Compound Ampules' },
    { value: 'BP Cuff - Pediatric', label: 'BP Cuff - Pediatric' },
    { value: 'Diphenhydramine Oral Suspension - Q-dryl 12.5mg per 5ml - 4 fl oz', label: 'Diphenhydramine Oral Suspension - Q-dryl 12.5mg per 5ml - 4 fl oz' },
    { value: 'Ear plugs (pairs)', label: 'Ear plugs (pairs)' },
    { value: 'Ibuprofen - Oral Suspension 100mg per 5ml - 4fl oz', label: 'Ibuprofen - Oral Suspension 100mg per 5ml - 4fl oz' },
    { value: 'Lidocaine Hydrochloride Jelly USP 2% - 20 mg/mL', label: 'Lidocaine Hydrochloride Jelly USP 2% - 20 mg/mL' },
    { value: "Loratadine Syrup - Children's - 5mg / ml - 4 fl oz", label: "Loratadine Syrup - Children's - 5mg/ml - 4 fl oz" },
    { value: 'Medicine Cups', label: 'Medicine Cups' },
    { value: 'O2 Mask - Pediatric', label: 'O2 Mask - Pediatric' },
    { value: 'Otoscope Specula - Pediatric - Pk of 35', label: 'Otoscope Specula - Pediatric - Pk of 35' },
    { value: 'Pedialyte - Oral Electrolyte - Individual Powder Packets', label: 'Pedialyte - Oral Electrolyte - Individual Powder Packets' },
];